{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lbg-app-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ if eq .path "/patients" }}{{ $.Values.patientService.name }}
            {{- else if eq .path "/appointments" }}{{ $.Values.appointmentService.name }}
            {{- else }}{{ $.Values.patientService.name }}{{- end }}
            port:
              number: {{ if eq .path "/patients" }}{{ $.Values.patientService.port }}
              {{- else if eq .path "/appointments" }}{{ $.Values.appointmentService.port }}
              {{- else }}{{ $.Values.patientService.port }}{{- end }}
      {{- end }}
      - path: /patient-service
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.patientService.name }}
            port:
              number: {{ $.Values.patientService.port }}
      - path: /appointment-service
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.appointmentService.name }}
            port:
              number: {{ $.Values.appointmentService.port }}
  {{- end }}
{{- end }}