apiVersion: v1
kind: Secret
metadata:
  name: lbg-app-secrets
  namespace: lbg-ns
type: Opaque
data:
  # These should be base64 encoded
  # echo -n "your-secret" | base64
  acr-username: YWNybGJnZGVtb2Rldg==
  acr-password: Y0xiaWMxbzBxUVBUK3ZIQkRzR1d6RkJaK1dBTjl4K1E1am5QZDlERGdLK0FDUkNMSjVMdA==